import { z } from 'zod';

export const IngredientSchema = z.object({
  name: z.string().min(1),
  normalizedName: z.string().min(1),
  quantity: z.number().positive(),
  unit: z.string().min(1),
  displayText: z.string().min(1),
  category: z.string().min(1),
  isOptional: z.boolean().default(false),
  isPantryItem: z.boolean().default(false),
  preparationNote: z.string().optional(),
  allergenFlags: z.array(z.string()).default([]),
});

export const RecipeStepSchema = z.object({
  order: z.number().int().positive(),
  instruction: z.string().min(1),
});

export const RecipeSchema = z.object({
  id: z.string().optional(), // generated by Firestore
  name: z.string().min(1),
  description: z.string().min(1),
  cuisine: z.string().min(1),
  originCountry: z.string().optional(),
  originCountryCode: z.string().optional(),
  dishClassification: z.string().min(1),
  authenticityLabel: z.enum(['traditional', 'widely_recognized', 'common_variation', 'adapted_to_preferences']),
  whyItFits: z.string().min(1),
  prepTimeMinutes: z.number().int().nonnegative(),
  cookTimeMinutes: z.number().int().nonnegative(),
  totalTimeMinutes: z.number().int().positive(),
  servings: z.number().int().positive(),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  equipment: z.array(z.string()),
  ingredients: z.array(IngredientSchema),
  preparationSteps: z.array(RecipeStepSchema),
  cookingSteps: z.array(RecipeStepSchema),
  presentationSuggestions: z.string().optional(),
  substitutions: z.array(z.string()).default([]),
  leftoverInstructions: z.string().optional(),
  foodSafetyNotes: z.string().optional(),
  allergenFlags: z.array(z.string()).default([]),
  dietaryTags: z.array(z.string()).default([]),
  sideDishSuggestion: z.string().optional(),
});

export const MealPlanGenerationInputSchema = z.object({
  planLength: z.enum(['3', '5', '7']),
  servings: z.number().int().positive(),
  maxTotalTimeMinutes: z.number().int().positive(),
  maxPrepTimeMinutes: z.number().int().positive().optional(),
  dietaryPattern: z.enum(['no_restriction', 'vegetarian', 'vegan', 'pescatarian', 'gluten_free', 'dairy_free', 'lower_carb', 'halal_friendly', 'kosher_style']).default('no_restriction'),
  allergens: z.array(z.string()).default([]),
  excludedIngredients: z.array(z.string()).default([]),
  preferredCuisines: z.array(z.string()).default([]),
  dislikedCuisines: z.array(z.string()).default([]),
  preferredProteins: z.array(z.string()).default([]),
  pantryIngredients: z.array(z.string()).default([]),
  useSoonIngredients: z.array(z.string()).default([]),
  availableEquipment: z.array(z.string()).default([]),
  skillLevel: z.enum(['beginner', 'intermediate', 'advanced']).default('intermediate'),
  budgetPreference: z.enum(['low', 'medium', 'high']).default('medium'),
  leftoverPreference: z.boolean().default(true),
  freeTextNotes: z.string().optional(),
});

export const GenerationMetadataSchema = z.object({
  modelName: z.string(),
  promptVersion: z.string(),
  generationTimestamp: z.string(), // ISO string
  generationDurationMs: z.number().int(),
  retryCount: z.number().int().nonnegative(),
  validationOutcome: z.enum(['success', 'repaired', 'failed']),
  estimatedRequestSizeBytes: z.number().int().optional(),
  userId: z.string(),
  planId: z.string().optional(),
  generationType: z.enum(['full_plan', 'recipe_regeneration']),
});

export const MealPlanSchema = z.object({
  id: z.string().optional(), // generated by Firestore
  name: z.string(),
  status: z.enum(['draft', 'generating', 'ready', 'failed', 'archived']),
  planLength: z.number().int().positive(),
  servings: z.number().int().positive(),
  generationInput: MealPlanGenerationInputSchema,
  summary: z.string().optional(),
  lockedRecipeIds: z.array(z.string()).default([]),
  shoppingListGenerated: z.boolean().default(false),
  promptVersion: z.string(),
  modelName: z.string(),
  recipes: z.array(RecipeSchema), // We can store them as subcollections later, but for Generation output it's nested
  metadata: GenerationMetadataSchema.optional(),
  shoppingList: z.array(z.any()).optional(),
  sharedId: z.string().optional(),
});

export const ShoppingListItemSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
  normalizedName: z.string(),
  quantity: z.number(),
  unit: z.string(),
  displayText: z.string(),
  category: z.string(),
  isPantryItem: z.boolean().default(false),
  isChecked: z.boolean().default(false),
  isCustom: z.boolean().default(false),
  sortOrder: z.number().int(),
});

export const RegenerationRequestSchema = z.object({
  planId: z.string(),
  recipeId: z.string(), // The recipe to replace
  reason: z.string().optional(),
  modifier: z.enum(['faster', 'cheaper', 'different_cuisine', 'different_protein', 'fewer_ingredients', 'more_familiar', 'use_pantry', 'avoid_ingredient']).optional(),
  avoidIngredient: z.string().optional(), // if modifier is 'avoid_ingredient'
  currentPlanState: MealPlanSchema, // to provide context to the AI
});

export type Ingredient = z.infer<typeof IngredientSchema>;
export type RecipeStep = z.infer<typeof RecipeStepSchema>;
export type Recipe = z.infer<typeof RecipeSchema>;
export type MealPlanGenerationInput = z.infer<typeof MealPlanGenerationInputSchema>;
export type GenerationMetadata = z.infer<typeof GenerationMetadataSchema>;
export type MealPlan = z.infer<typeof MealPlanSchema>;
export type ShoppingListItem = z.infer<typeof ShoppingListItemSchema>;
export type RegenerationRequest = z.infer<typeof RegenerationRequestSchema>;
