"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegenerationRequestSchema = exports.ShoppingListItemSchema = exports.MealPlanSchema = exports.GenerationMetadataSchema = exports.MealPlanGenerationInputSchema = exports.RecipeSchema = exports.RecipeStepSchema = exports.IngredientSchema = void 0;
const zod_1 = require("zod");
exports.IngredientSchema = zod_1.z.object({
    name: zod_1.z.string().min(1),
    normalizedName: zod_1.z.string().min(1),
    quantity: zod_1.z.number().positive(),
    unit: zod_1.z.string().min(1),
    displayText: zod_1.z.string().min(1),
    category: zod_1.z.string().min(1),
    isOptional: zod_1.z.boolean().default(false),
    isPantryItem: zod_1.z.boolean().default(false),
    preparationNote: zod_1.z.string().optional(),
    allergenFlags: zod_1.z.array(zod_1.z.string()).default([]),
});
exports.RecipeStepSchema = zod_1.z.object({
    order: zod_1.z.number().int().positive(),
    instruction: zod_1.z.string().min(1),
});
exports.RecipeSchema = zod_1.z.object({
    id: zod_1.z.string().optional(), // generated by Firestore
    name: zod_1.z.string().min(1),
    description: zod_1.z.string().min(1),
    cuisine: zod_1.z.string().min(1),
    originCountry: zod_1.z.string().optional(),
    originCountryCode: zod_1.z.string().optional(),
    dishClassification: zod_1.z.string().min(1),
    authenticityLabel: zod_1.z.enum(['traditional', 'widely_recognized', 'common_variation', 'adapted_to_preferences']),
    whyItFits: zod_1.z.string().min(1),
    prepTimeMinutes: zod_1.z.number().int().nonnegative(),
    cookTimeMinutes: zod_1.z.number().int().nonnegative(),
    totalTimeMinutes: zod_1.z.number().int().positive(),
    servings: zod_1.z.number().int().positive(),
    difficulty: zod_1.z.enum(['easy', 'medium', 'hard']),
    equipment: zod_1.z.array(zod_1.z.string()),
    ingredients: zod_1.z.array(exports.IngredientSchema),
    preparationSteps: zod_1.z.array(exports.RecipeStepSchema),
    cookingSteps: zod_1.z.array(exports.RecipeStepSchema),
    presentationSuggestions: zod_1.z.string().optional(),
    substitutions: zod_1.z.array(zod_1.z.string()).default([]),
    leftoverInstructions: zod_1.z.string().optional(),
    foodSafetyNotes: zod_1.z.string().optional(),
    allergenFlags: zod_1.z.array(zod_1.z.string()).default([]),
    dietaryTags: zod_1.z.array(zod_1.z.string()).default([]),
    sideDishSuggestion: zod_1.z.string().optional(),
});
exports.MealPlanGenerationInputSchema = zod_1.z.object({
    planLength: zod_1.z.enum(['3', '5', '7']),
    servings: zod_1.z.number().int().positive(),
    maxTotalTimeMinutes: zod_1.z.number().int().positive(),
    maxPrepTimeMinutes: zod_1.z.number().int().positive().optional(),
    dietaryPattern: zod_1.z.enum(['no_restriction', 'vegetarian', 'vegan', 'pescatarian', 'gluten_free', 'dairy_free', 'lower_carb', 'halal_friendly', 'kosher_style']).default('no_restriction'),
    allergens: zod_1.z.array(zod_1.z.string()).default([]),
    excludedIngredients: zod_1.z.array(zod_1.z.string()).default([]),
    preferredCuisines: zod_1.z.array(zod_1.z.string()).default([]),
    dislikedCuisines: zod_1.z.array(zod_1.z.string()).default([]),
    preferredProteins: zod_1.z.array(zod_1.z.string()).default([]),
    pantryIngredients: zod_1.z.array(zod_1.z.string()).default([]),
    useSoonIngredients: zod_1.z.array(zod_1.z.string()).default([]),
    availableEquipment: zod_1.z.array(zod_1.z.string()).default([]),
    skillLevel: zod_1.z.enum(['beginner', 'intermediate', 'advanced']).default('intermediate'),
    budgetPreference: zod_1.z.enum(['low', 'medium', 'high']).default('medium'),
    leftoverPreference: zod_1.z.boolean().default(true),
    freeTextNotes: zod_1.z.string().optional(),
});
exports.GenerationMetadataSchema = zod_1.z.object({
    modelName: zod_1.z.string(),
    promptVersion: zod_1.z.string(),
    generationTimestamp: zod_1.z.string(), // ISO string
    generationDurationMs: zod_1.z.number().int(),
    retryCount: zod_1.z.number().int().nonnegative(),
    validationOutcome: zod_1.z.enum(['success', 'repaired', 'failed']),
    estimatedRequestSizeBytes: zod_1.z.number().int().optional(),
    userId: zod_1.z.string(),
    planId: zod_1.z.string().optional(),
    generationType: zod_1.z.enum(['full_plan', 'recipe_regeneration']),
});
exports.MealPlanSchema = zod_1.z.object({
    id: zod_1.z.string().optional(), // generated by Firestore
    name: zod_1.z.string(),
    status: zod_1.z.enum(['draft', 'generating', 'ready', 'failed', 'archived']),
    planLength: zod_1.z.number().int().positive(),
    servings: zod_1.z.number().int().positive(),
    generationInput: exports.MealPlanGenerationInputSchema,
    summary: zod_1.z.string().optional(),
    lockedRecipeIds: zod_1.z.array(zod_1.z.string()).default([]),
    shoppingListGenerated: zod_1.z.boolean().default(false),
    promptVersion: zod_1.z.string(),
    modelName: zod_1.z.string(),
    recipes: zod_1.z.array(exports.RecipeSchema), // We can store them as subcollections later, but for Generation output it's nested
    metadata: exports.GenerationMetadataSchema.optional(),
});
exports.ShoppingListItemSchema = zod_1.z.object({
    id: zod_1.z.string().optional(),
    name: zod_1.z.string(),
    normalizedName: zod_1.z.string(),
    quantity: zod_1.z.number(),
    unit: zod_1.z.string(),
    displayText: zod_1.z.string(),
    category: zod_1.z.string(),
    isPantryItem: zod_1.z.boolean().default(false),
    isChecked: zod_1.z.boolean().default(false),
    isCustom: zod_1.z.boolean().default(false),
    sortOrder: zod_1.z.number().int(),
});
exports.RegenerationRequestSchema = zod_1.z.object({
    planId: zod_1.z.string(),
    recipeId: zod_1.z.string(), // The recipe to replace
    reason: zod_1.z.string().optional(),
    modifier: zod_1.z.enum(['faster', 'cheaper', 'different_cuisine', 'different_protein', 'fewer_ingredients', 'more_familiar', 'use_pantry', 'avoid_ingredient']).optional(),
    avoidIngredient: zod_1.z.string().optional(), // if modifier is 'avoid_ingredient'
    currentPlanState: exports.MealPlanSchema, // to provide context to the AI
});
//# sourceMappingURL=schemas.js.map